version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
